apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    path: apps/external-secrets
    repoURL: 'https://github.com/aabualru/apps.git'
    targetRevision: main